import { ProviderRedux } from '@/redux/provider'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <div className='bg-gradient-to-br from-gray-700 via-gray-900 to-black h-screen'>
          <ProviderRedux>{children}</ProviderRedux>
        </div>
      </body>
    </html>
  )
}
